### PR TITLE
prov/verbs: Remove XRC domain file when no longer by any process on t…

### PR DESCRIPTION
**Pull request by swelch**
…he node

This is a linux specific solution to cleanup the XRC domain file shared
among processes within the same XRC domain. This solution will cleanup
the file under normal operation, but will not remove the file in the event
of a process abort. If an abort occurs and the next process to open the
XRC domain file is not running as the same user, then the file will need
to be manually removed. The implementation attempts to use file descriptor
locking not process, so that a single process can create multiple domains
and the code will work as intended (this requires linux 3.15 and later).

Signed-off-by: Steve Welch <swelch@systemfabricworks.com>

Note that this implementation is targeting internal use, and also that it
will not work concurrently with the previous implementation running
on the same nodes. Any existing XRCD domain file will need to be
deleted. It is advisable to still set the environment variable:

export FI_VERBS_XRCD_FILENAME=/tmp/something_user_unique_xrcd

### CODE REVIEW

**Comment by swelch** [comment]
This is intended as a Linux specific solution for issue 489.

**Comment by jswaro** [comment]
Why can't we use unlink again?

**Comment by swelch** [comment]
> Why can't we use unlink again?

The problem I had with unlinking the file after the open (so it would go away automatically after the last close), was determining how it could be done at the time of the open and still allow other processes to open the file. That is, following the unlink, the file remains open until the last open closes it, but it is not visible from the directory so if you attempt to open it it will create a new file.

I'm can't say there isn't a way to do it that I don't know about, but I made a reasonable search trying to find a solution and could not find one.

**Comment by jswaro** [comment]
I'm not sure I've seen that problem. I've used mmap with files to share memory between processes and used unlink as a clean-up mechanism.

The man page seems to indicate that the name will stick around until the process dies if we don't close the file descriptor and let it die at process exit.

> If the name was the last link to a file but any processes still have the file open the file will remain in existence until the last file descriptor referring to it is closed.

**Comment by swelch** [comment]
> I'm not sure I've seen that problem. I've used mmap with files to share memory between processes and used unlink as a clean-up mechanism.
> 
> The man page seems to indicate that the name will stick around until the process dies if we don't close the file descriptor and let it die at process exit.
> 
> > If the name was the last link to a file but any processes still have the file open the file will remain in existence until the last file descriptor referring to it is closed.

That is what I'm saying, I thought. With the unlink() without a close, the file stays in existence but it is unlinked from the directory, right? Unlink removes the directory i-node, the file still exists and can be written/read, etc. by those that already have it open. My reading of it doesn't indicate to me you can still open the file after the unlink, only that the file remains until all existing opens have closed it. Are you saying I should be able to; I can double check again if you know that is correct?

**Comment by jswaro** [comment]
I think how it works, is that the i-node is pending removal when the last reference is dropped. Other processes should be able to open the file. We can do a simple test or two.

**Comment by swelch** [comment]
> I think how it works, is that the i-node is pending removal when the last reference is dropped. Other processes should be able to open the file. We can do a simple test or two.

I'll check again.

**Comment by jswaro** [comment]
This needs to be rebased.

**Comment by swelch** [comment]
> This needs to be rebased.

This PR is really old, I rebased the development branch in my private area on newer OFIWG master code so I could test with the latest. I was not planning on going through SFW repository, but can rebase off of SFW master if you prefer and/or want to test with it. Thanks.

**Comment by jswaro** [comment]
Oh. This isn’t the new branch ?

-- Jim

**Comment by swelch** [comment]
@jswaro - OK, I figured out what hoops to jump through to get the commit and the integration branch in sync with each other so that we can maintain the PR history. I'm going to test with this update later today to make sure all is still fine.

**Comment by swelch** [comment]
@jswaro - I tested this at scale using some OSU bench marks and shared memory, and didn't see any issues. The failures in CI looked to be related to not being able to delete workspace files/directories.

**Pull request closed without merging**
